/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafmongo.kafmongo.utils;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class IndexRTSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4773270635382231355L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IndexRTSchema\",\"namespace\":\"com.kafmongo.kafmongo.utils\",\"fields\":[{\"name\":\"field_market_capitalisation\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"field_transact_time\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"field_index_value\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"field_divisor\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"field_index_low_value\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"field_index_high_value\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"field_var_year\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"field_var_veille\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"veille\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"index\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"index_url\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IndexRTSchema> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IndexRTSchema> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<IndexRTSchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<IndexRTSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<IndexRTSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this IndexRTSchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a IndexRTSchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a IndexRTSchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static IndexRTSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence field_market_capitalisation;
  private java.lang.CharSequence field_transact_time;
  private java.lang.CharSequence field_index_value;
  private java.lang.CharSequence field_divisor;
  private java.lang.CharSequence field_index_low_value;
  private java.lang.CharSequence field_index_high_value;
  private java.lang.CharSequence field_var_year;
  private java.lang.CharSequence field_var_veille;
  private java.lang.CharSequence veille;
  private java.lang.CharSequence index;
  private java.lang.CharSequence index_url;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IndexRTSchema() {}

  /**
   * All-args constructor.
   * @param field_market_capitalisation The new value for field_market_capitalisation
   * @param field_transact_time The new value for field_transact_time
   * @param field_index_value The new value for field_index_value
   * @param field_divisor The new value for field_divisor
   * @param field_index_low_value The new value for field_index_low_value
   * @param field_index_high_value The new value for field_index_high_value
   * @param field_var_year The new value for field_var_year
   * @param field_var_veille The new value for field_var_veille
   * @param veille The new value for veille
   * @param index The new value for index
   * @param index_url The new value for index_url
   */
  public IndexRTSchema(java.lang.CharSequence field_market_capitalisation, java.lang.CharSequence field_transact_time, java.lang.CharSequence field_index_value, java.lang.CharSequence field_divisor, java.lang.CharSequence field_index_low_value, java.lang.CharSequence field_index_high_value, java.lang.CharSequence field_var_year, java.lang.CharSequence field_var_veille, java.lang.CharSequence veille, java.lang.CharSequence index, java.lang.CharSequence index_url) {
    this.field_market_capitalisation = field_market_capitalisation;
    this.field_transact_time = field_transact_time;
    this.field_index_value = field_index_value;
    this.field_divisor = field_divisor;
    this.field_index_low_value = field_index_low_value;
    this.field_index_high_value = field_index_high_value;
    this.field_var_year = field_var_year;
    this.field_var_veille = field_var_veille;
    this.veille = veille;
    this.index = index;
    this.index_url = index_url;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return field_market_capitalisation;
    case 1: return field_transact_time;
    case 2: return field_index_value;
    case 3: return field_divisor;
    case 4: return field_index_low_value;
    case 5: return field_index_high_value;
    case 6: return field_var_year;
    case 7: return field_var_veille;
    case 8: return veille;
    case 9: return index;
    case 10: return index_url;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: field_market_capitalisation = (java.lang.CharSequence)value$; break;
    case 1: field_transact_time = (java.lang.CharSequence)value$; break;
    case 2: field_index_value = (java.lang.CharSequence)value$; break;
    case 3: field_divisor = (java.lang.CharSequence)value$; break;
    case 4: field_index_low_value = (java.lang.CharSequence)value$; break;
    case 5: field_index_high_value = (java.lang.CharSequence)value$; break;
    case 6: field_var_year = (java.lang.CharSequence)value$; break;
    case 7: field_var_veille = (java.lang.CharSequence)value$; break;
    case 8: veille = (java.lang.CharSequence)value$; break;
    case 9: index = (java.lang.CharSequence)value$; break;
    case 10: index_url = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'field_market_capitalisation' field.
   * @return The value of the 'field_market_capitalisation' field.
   */
  public java.lang.CharSequence getFieldMarketCapitalisation() {
    return field_market_capitalisation;
  }


  /**
   * Sets the value of the 'field_market_capitalisation' field.
   * @param value the value to set.
   */
  public void setFieldMarketCapitalisation(java.lang.CharSequence value) {
    this.field_market_capitalisation = value;
  }

  /**
   * Gets the value of the 'field_transact_time' field.
   * @return The value of the 'field_transact_time' field.
   */
  public java.lang.CharSequence getFieldTransactTime() {
    return field_transact_time;
  }


  /**
   * Sets the value of the 'field_transact_time' field.
   * @param value the value to set.
   */
  public void setFieldTransactTime(java.lang.CharSequence value) {
    this.field_transact_time = value;
  }

  /**
   * Gets the value of the 'field_index_value' field.
   * @return The value of the 'field_index_value' field.
   */
  public java.lang.CharSequence getFieldIndexValue() {
    return field_index_value;
  }


  /**
   * Sets the value of the 'field_index_value' field.
   * @param value the value to set.
   */
  public void setFieldIndexValue(java.lang.CharSequence value) {
    this.field_index_value = value;
  }

  /**
   * Gets the value of the 'field_divisor' field.
   * @return The value of the 'field_divisor' field.
   */
  public java.lang.CharSequence getFieldDivisor() {
    return field_divisor;
  }


  /**
   * Sets the value of the 'field_divisor' field.
   * @param value the value to set.
   */
  public void setFieldDivisor(java.lang.CharSequence value) {
    this.field_divisor = value;
  }

  /**
   * Gets the value of the 'field_index_low_value' field.
   * @return The value of the 'field_index_low_value' field.
   */
  public java.lang.CharSequence getFieldIndexLowValue() {
    return field_index_low_value;
  }


  /**
   * Sets the value of the 'field_index_low_value' field.
   * @param value the value to set.
   */
  public void setFieldIndexLowValue(java.lang.CharSequence value) {
    this.field_index_low_value = value;
  }

  /**
   * Gets the value of the 'field_index_high_value' field.
   * @return The value of the 'field_index_high_value' field.
   */
  public java.lang.CharSequence getFieldIndexHighValue() {
    return field_index_high_value;
  }


  /**
   * Sets the value of the 'field_index_high_value' field.
   * @param value the value to set.
   */
  public void setFieldIndexHighValue(java.lang.CharSequence value) {
    this.field_index_high_value = value;
  }

  /**
   * Gets the value of the 'field_var_year' field.
   * @return The value of the 'field_var_year' field.
   */
  public java.lang.CharSequence getFieldVarYear() {
    return field_var_year;
  }


  /**
   * Sets the value of the 'field_var_year' field.
   * @param value the value to set.
   */
  public void setFieldVarYear(java.lang.CharSequence value) {
    this.field_var_year = value;
  }

  /**
   * Gets the value of the 'field_var_veille' field.
   * @return The value of the 'field_var_veille' field.
   */
  public java.lang.CharSequence getFieldVarVeille() {
    return field_var_veille;
  }


  /**
   * Sets the value of the 'field_var_veille' field.
   * @param value the value to set.
   */
  public void setFieldVarVeille(java.lang.CharSequence value) {
    this.field_var_veille = value;
  }

  /**
   * Gets the value of the 'veille' field.
   * @return The value of the 'veille' field.
   */
  public java.lang.CharSequence getVeille() {
    return veille;
  }


  /**
   * Sets the value of the 'veille' field.
   * @param value the value to set.
   */
  public void setVeille(java.lang.CharSequence value) {
    this.veille = value;
  }

  /**
   * Gets the value of the 'index' field.
   * @return The value of the 'index' field.
   */
  public java.lang.CharSequence getIndex() {
    return index;
  }


  /**
   * Sets the value of the 'index' field.
   * @param value the value to set.
   */
  public void setIndex(java.lang.CharSequence value) {
    this.index = value;
  }

  /**
   * Gets the value of the 'index_url' field.
   * @return The value of the 'index_url' field.
   */
  public java.lang.CharSequence getIndexUrl() {
    return index_url;
  }


  /**
   * Sets the value of the 'index_url' field.
   * @param value the value to set.
   */
  public void setIndexUrl(java.lang.CharSequence value) {
    this.index_url = value;
  }

  /**
   * Creates a new IndexRTSchema RecordBuilder.
   * @return A new IndexRTSchema RecordBuilder
   */
  public static com.kafmongo.kafmongo.utils.IndexRTSchema.Builder newBuilder() {
    return new com.kafmongo.kafmongo.utils.IndexRTSchema.Builder();
  }

  /**
   * Creates a new IndexRTSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IndexRTSchema RecordBuilder
   */
  public static com.kafmongo.kafmongo.utils.IndexRTSchema.Builder newBuilder(com.kafmongo.kafmongo.utils.IndexRTSchema.Builder other) {
    if (other == null) {
      return new com.kafmongo.kafmongo.utils.IndexRTSchema.Builder();
    } else {
      return new com.kafmongo.kafmongo.utils.IndexRTSchema.Builder(other);
    }
  }

  /**
   * Creates a new IndexRTSchema RecordBuilder by copying an existing IndexRTSchema instance.
   * @param other The existing instance to copy.
   * @return A new IndexRTSchema RecordBuilder
   */
  public static com.kafmongo.kafmongo.utils.IndexRTSchema.Builder newBuilder(com.kafmongo.kafmongo.utils.IndexRTSchema other) {
    if (other == null) {
      return new com.kafmongo.kafmongo.utils.IndexRTSchema.Builder();
    } else {
      return new com.kafmongo.kafmongo.utils.IndexRTSchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for IndexRTSchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IndexRTSchema>
    implements org.apache.avro.data.RecordBuilder<IndexRTSchema> {

    private java.lang.CharSequence field_market_capitalisation;
    private java.lang.CharSequence field_transact_time;
    private java.lang.CharSequence field_index_value;
    private java.lang.CharSequence field_divisor;
    private java.lang.CharSequence field_index_low_value;
    private java.lang.CharSequence field_index_high_value;
    private java.lang.CharSequence field_var_year;
    private java.lang.CharSequence field_var_veille;
    private java.lang.CharSequence veille;
    private java.lang.CharSequence index;
    private java.lang.CharSequence index_url;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafmongo.kafmongo.utils.IndexRTSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.field_market_capitalisation)) {
        this.field_market_capitalisation = data().deepCopy(fields()[0].schema(), other.field_market_capitalisation);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.field_transact_time)) {
        this.field_transact_time = data().deepCopy(fields()[1].schema(), other.field_transact_time);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.field_index_value)) {
        this.field_index_value = data().deepCopy(fields()[2].schema(), other.field_index_value);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.field_divisor)) {
        this.field_divisor = data().deepCopy(fields()[3].schema(), other.field_divisor);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.field_index_low_value)) {
        this.field_index_low_value = data().deepCopy(fields()[4].schema(), other.field_index_low_value);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.field_index_high_value)) {
        this.field_index_high_value = data().deepCopy(fields()[5].schema(), other.field_index_high_value);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.field_var_year)) {
        this.field_var_year = data().deepCopy(fields()[6].schema(), other.field_var_year);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.field_var_veille)) {
        this.field_var_veille = data().deepCopy(fields()[7].schema(), other.field_var_veille);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.veille)) {
        this.veille = data().deepCopy(fields()[8].schema(), other.veille);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.index)) {
        this.index = data().deepCopy(fields()[9].schema(), other.index);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.index_url)) {
        this.index_url = data().deepCopy(fields()[10].schema(), other.index_url);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing IndexRTSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafmongo.kafmongo.utils.IndexRTSchema other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.field_market_capitalisation)) {
        this.field_market_capitalisation = data().deepCopy(fields()[0].schema(), other.field_market_capitalisation);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.field_transact_time)) {
        this.field_transact_time = data().deepCopy(fields()[1].schema(), other.field_transact_time);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.field_index_value)) {
        this.field_index_value = data().deepCopy(fields()[2].schema(), other.field_index_value);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.field_divisor)) {
        this.field_divisor = data().deepCopy(fields()[3].schema(), other.field_divisor);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.field_index_low_value)) {
        this.field_index_low_value = data().deepCopy(fields()[4].schema(), other.field_index_low_value);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.field_index_high_value)) {
        this.field_index_high_value = data().deepCopy(fields()[5].schema(), other.field_index_high_value);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.field_var_year)) {
        this.field_var_year = data().deepCopy(fields()[6].schema(), other.field_var_year);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.field_var_veille)) {
        this.field_var_veille = data().deepCopy(fields()[7].schema(), other.field_var_veille);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.veille)) {
        this.veille = data().deepCopy(fields()[8].schema(), other.veille);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.index)) {
        this.index = data().deepCopy(fields()[9].schema(), other.index);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.index_url)) {
        this.index_url = data().deepCopy(fields()[10].schema(), other.index_url);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'field_market_capitalisation' field.
      * @return The value.
      */
    public java.lang.CharSequence getFieldMarketCapitalisation() {
      return field_market_capitalisation;
    }


    /**
      * Sets the value of the 'field_market_capitalisation' field.
      * @param value The value of 'field_market_capitalisation'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setFieldMarketCapitalisation(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.field_market_capitalisation = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'field_market_capitalisation' field has been set.
      * @return True if the 'field_market_capitalisation' field has been set, false otherwise.
      */
    public boolean hasFieldMarketCapitalisation() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'field_market_capitalisation' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearFieldMarketCapitalisation() {
      field_market_capitalisation = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'field_transact_time' field.
      * @return The value.
      */
    public java.lang.CharSequence getFieldTransactTime() {
      return field_transact_time;
    }


    /**
      * Sets the value of the 'field_transact_time' field.
      * @param value The value of 'field_transact_time'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setFieldTransactTime(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.field_transact_time = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'field_transact_time' field has been set.
      * @return True if the 'field_transact_time' field has been set, false otherwise.
      */
    public boolean hasFieldTransactTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'field_transact_time' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearFieldTransactTime() {
      field_transact_time = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'field_index_value' field.
      * @return The value.
      */
    public java.lang.CharSequence getFieldIndexValue() {
      return field_index_value;
    }


    /**
      * Sets the value of the 'field_index_value' field.
      * @param value The value of 'field_index_value'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setFieldIndexValue(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.field_index_value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'field_index_value' field has been set.
      * @return True if the 'field_index_value' field has been set, false otherwise.
      */
    public boolean hasFieldIndexValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'field_index_value' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearFieldIndexValue() {
      field_index_value = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'field_divisor' field.
      * @return The value.
      */
    public java.lang.CharSequence getFieldDivisor() {
      return field_divisor;
    }


    /**
      * Sets the value of the 'field_divisor' field.
      * @param value The value of 'field_divisor'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setFieldDivisor(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.field_divisor = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'field_divisor' field has been set.
      * @return True if the 'field_divisor' field has been set, false otherwise.
      */
    public boolean hasFieldDivisor() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'field_divisor' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearFieldDivisor() {
      field_divisor = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'field_index_low_value' field.
      * @return The value.
      */
    public java.lang.CharSequence getFieldIndexLowValue() {
      return field_index_low_value;
    }


    /**
      * Sets the value of the 'field_index_low_value' field.
      * @param value The value of 'field_index_low_value'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setFieldIndexLowValue(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.field_index_low_value = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'field_index_low_value' field has been set.
      * @return True if the 'field_index_low_value' field has been set, false otherwise.
      */
    public boolean hasFieldIndexLowValue() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'field_index_low_value' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearFieldIndexLowValue() {
      field_index_low_value = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'field_index_high_value' field.
      * @return The value.
      */
    public java.lang.CharSequence getFieldIndexHighValue() {
      return field_index_high_value;
    }


    /**
      * Sets the value of the 'field_index_high_value' field.
      * @param value The value of 'field_index_high_value'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setFieldIndexHighValue(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.field_index_high_value = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'field_index_high_value' field has been set.
      * @return True if the 'field_index_high_value' field has been set, false otherwise.
      */
    public boolean hasFieldIndexHighValue() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'field_index_high_value' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearFieldIndexHighValue() {
      field_index_high_value = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'field_var_year' field.
      * @return The value.
      */
    public java.lang.CharSequence getFieldVarYear() {
      return field_var_year;
    }


    /**
      * Sets the value of the 'field_var_year' field.
      * @param value The value of 'field_var_year'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setFieldVarYear(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.field_var_year = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'field_var_year' field has been set.
      * @return True if the 'field_var_year' field has been set, false otherwise.
      */
    public boolean hasFieldVarYear() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'field_var_year' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearFieldVarYear() {
      field_var_year = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'field_var_veille' field.
      * @return The value.
      */
    public java.lang.CharSequence getFieldVarVeille() {
      return field_var_veille;
    }


    /**
      * Sets the value of the 'field_var_veille' field.
      * @param value The value of 'field_var_veille'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setFieldVarVeille(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.field_var_veille = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'field_var_veille' field has been set.
      * @return True if the 'field_var_veille' field has been set, false otherwise.
      */
    public boolean hasFieldVarVeille() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'field_var_veille' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearFieldVarVeille() {
      field_var_veille = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'veille' field.
      * @return The value.
      */
    public java.lang.CharSequence getVeille() {
      return veille;
    }


    /**
      * Sets the value of the 'veille' field.
      * @param value The value of 'veille'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setVeille(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.veille = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'veille' field has been set.
      * @return True if the 'veille' field has been set, false otherwise.
      */
    public boolean hasVeille() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'veille' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearVeille() {
      veille = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'index' field.
      * @return The value.
      */
    public java.lang.CharSequence getIndex() {
      return index;
    }


    /**
      * Sets the value of the 'index' field.
      * @param value The value of 'index'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setIndex(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.index = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'index' field has been set.
      * @return True if the 'index' field has been set, false otherwise.
      */
    public boolean hasIndex() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'index' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearIndex() {
      index = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'index_url' field.
      * @return The value.
      */
    public java.lang.CharSequence getIndexUrl() {
      return index_url;
    }


    /**
      * Sets the value of the 'index_url' field.
      * @param value The value of 'index_url'.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder setIndexUrl(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.index_url = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'index_url' field has been set.
      * @return True if the 'index_url' field has been set, false otherwise.
      */
    public boolean hasIndexUrl() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'index_url' field.
      * @return This builder.
      */
    public com.kafmongo.kafmongo.utils.IndexRTSchema.Builder clearIndexUrl() {
      index_url = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IndexRTSchema build() {
      try {
        IndexRTSchema record = new IndexRTSchema();
        record.field_market_capitalisation = fieldSetFlags()[0] ? this.field_market_capitalisation : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.field_transact_time = fieldSetFlags()[1] ? this.field_transact_time : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.field_index_value = fieldSetFlags()[2] ? this.field_index_value : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.field_divisor = fieldSetFlags()[3] ? this.field_divisor : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.field_index_low_value = fieldSetFlags()[4] ? this.field_index_low_value : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.field_index_high_value = fieldSetFlags()[5] ? this.field_index_high_value : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.field_var_year = fieldSetFlags()[6] ? this.field_var_year : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.field_var_veille = fieldSetFlags()[7] ? this.field_var_veille : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.veille = fieldSetFlags()[8] ? this.veille : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.index = fieldSetFlags()[9] ? this.index : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.index_url = fieldSetFlags()[10] ? this.index_url : (java.lang.CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IndexRTSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<IndexRTSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IndexRTSchema>
    READER$ = (org.apache.avro.io.DatumReader<IndexRTSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.field_market_capitalisation == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.field_market_capitalisation);
    }

    if (this.field_transact_time == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.field_transact_time);
    }

    if (this.field_index_value == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.field_index_value);
    }

    if (this.field_divisor == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.field_divisor);
    }

    if (this.field_index_low_value == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.field_index_low_value);
    }

    if (this.field_index_high_value == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.field_index_high_value);
    }

    if (this.field_var_year == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.field_var_year);
    }

    if (this.field_var_veille == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.field_var_veille);
    }

    if (this.veille == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.veille);
    }

    if (this.index == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.index);
    }

    if (this.index_url == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.index_url);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.field_market_capitalisation = null;
      } else {
        this.field_market_capitalisation = in.readString(this.field_market_capitalisation instanceof Utf8 ? (Utf8)this.field_market_capitalisation : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.field_transact_time = null;
      } else {
        this.field_transact_time = in.readString(this.field_transact_time instanceof Utf8 ? (Utf8)this.field_transact_time : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.field_index_value = null;
      } else {
        this.field_index_value = in.readString(this.field_index_value instanceof Utf8 ? (Utf8)this.field_index_value : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.field_divisor = null;
      } else {
        this.field_divisor = in.readString(this.field_divisor instanceof Utf8 ? (Utf8)this.field_divisor : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.field_index_low_value = null;
      } else {
        this.field_index_low_value = in.readString(this.field_index_low_value instanceof Utf8 ? (Utf8)this.field_index_low_value : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.field_index_high_value = null;
      } else {
        this.field_index_high_value = in.readString(this.field_index_high_value instanceof Utf8 ? (Utf8)this.field_index_high_value : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.field_var_year = null;
      } else {
        this.field_var_year = in.readString(this.field_var_year instanceof Utf8 ? (Utf8)this.field_var_year : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.field_var_veille = null;
      } else {
        this.field_var_veille = in.readString(this.field_var_veille instanceof Utf8 ? (Utf8)this.field_var_veille : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.veille = null;
      } else {
        this.veille = in.readString(this.veille instanceof Utf8 ? (Utf8)this.veille : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.index = null;
      } else {
        this.index = in.readString(this.index instanceof Utf8 ? (Utf8)this.index : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.index_url = null;
      } else {
        this.index_url = in.readString(this.index_url instanceof Utf8 ? (Utf8)this.index_url : null);
      }

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.field_market_capitalisation = null;
          } else {
            this.field_market_capitalisation = in.readString(this.field_market_capitalisation instanceof Utf8 ? (Utf8)this.field_market_capitalisation : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.field_transact_time = null;
          } else {
            this.field_transact_time = in.readString(this.field_transact_time instanceof Utf8 ? (Utf8)this.field_transact_time : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.field_index_value = null;
          } else {
            this.field_index_value = in.readString(this.field_index_value instanceof Utf8 ? (Utf8)this.field_index_value : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.field_divisor = null;
          } else {
            this.field_divisor = in.readString(this.field_divisor instanceof Utf8 ? (Utf8)this.field_divisor : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.field_index_low_value = null;
          } else {
            this.field_index_low_value = in.readString(this.field_index_low_value instanceof Utf8 ? (Utf8)this.field_index_low_value : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.field_index_high_value = null;
          } else {
            this.field_index_high_value = in.readString(this.field_index_high_value instanceof Utf8 ? (Utf8)this.field_index_high_value : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.field_var_year = null;
          } else {
            this.field_var_year = in.readString(this.field_var_year instanceof Utf8 ? (Utf8)this.field_var_year : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.field_var_veille = null;
          } else {
            this.field_var_veille = in.readString(this.field_var_veille instanceof Utf8 ? (Utf8)this.field_var_veille : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.veille = null;
          } else {
            this.veille = in.readString(this.veille instanceof Utf8 ? (Utf8)this.veille : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.index = null;
          } else {
            this.index = in.readString(this.index instanceof Utf8 ? (Utf8)this.index : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.index_url = null;
          } else {
            this.index_url = in.readString(this.index_url instanceof Utf8 ? (Utf8)this.index_url : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










