/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.popupd.util;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BourseData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -8493464003917961857L;


    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BourseData\",\"namespace\":\"com.popupd.util\",\"fields\":[{\"name\":\"field_date_application\",\"type\":\"string\"},{\"name\":\"field_closing_price\",\"type\":\"string\"},{\"name\":\"field_difference\",\"type\":\"string\"},{\"name\":\"field_var_veille\",\"type\":\"string\"},{\"name\":\"field_best_ask_size\",\"type\":\"string\"},{\"name\":\"field_transact_time\",\"type\":\"string\"},{\"name\":\"field_cours_cloture\",\"type\":\"string\"},{\"name\":\"field_cours_ajuste\",\"type\":\"string\"},{\"name\":\"field_cumul_titres_echanges\",\"type\":\"string\"},{\"name\":\"field_best_bid_size\",\"type\":\"string\"},{\"name\":\"field_capitalisation\",\"type\":\"string\"},{\"name\":\"field_opening_price\",\"type\":\"string\"},{\"name\":\"field_total_trades\",\"type\":\"string\"},{\"name\":\"field_cours_courant\",\"type\":\"string\"},{\"name\":\"field_best_ask_price\",\"type\":\"string\"},{\"name\":\"sous_secteur\",\"type\":\"string\"},{\"name\":\"ticker\",\"type\":\"string\"},{\"name\":\"field_instrument_var_year\",\"type\":\"string\"},{\"name\":\"field_var_pto\",\"type\":\"string\"},{\"name\":\"field_last_traded_time\",\"type\":\"string\"},{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"field_best_bid_price\",\"type\":\"string\"},{\"name\":\"field_dynamic_reference_price\",\"type\":\"string\"},{\"name\":\"field_static_reference_price\",\"type\":\"string\"},{\"name\":\"field_low_price\",\"type\":\"string\"},{\"name\":\"field_high_price\",\"type\":\"string\"},{\"name\":\"field_cumul_volume_echange\",\"type\":\"string\"},{\"name\":\"field_last_traded_price\",\"type\":\"string\"}]}");
    public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

    private static final SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<BourseData> ENCODER =
            new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<BourseData> DECODER =
            new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<BourseData> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<BourseData> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<BourseData> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this BourseData to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a BourseData from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a BourseData instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static BourseData fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private java.lang.CharSequence field_date_application;
    private java.lang.CharSequence field_closing_price;
    private java.lang.CharSequence field_difference;
    private java.lang.CharSequence field_var_veille;
    private java.lang.CharSequence field_best_ask_size;
    private java.lang.CharSequence field_transact_time;
    private java.lang.CharSequence field_cours_cloture;
    private java.lang.CharSequence field_cours_ajuste;
    private java.lang.CharSequence field_cumul_titres_echanges;
    private java.lang.CharSequence field_best_bid_size;
    private java.lang.CharSequence field_capitalisation;
    private java.lang.CharSequence field_opening_price;
    private java.lang.CharSequence field_total_trades;
    private java.lang.CharSequence field_cours_courant;
    private java.lang.CharSequence field_best_ask_price;
    private java.lang.CharSequence sous_secteur;
    private java.lang.CharSequence ticker;
    private java.lang.CharSequence field_instrument_var_year;
    private java.lang.CharSequence field_var_pto;
    private java.lang.CharSequence field_last_traded_time;
    private java.lang.CharSequence label;
    private java.lang.CharSequence field_best_bid_price;
    private java.lang.CharSequence field_dynamic_reference_price;
    private java.lang.CharSequence field_static_reference_price;
    private java.lang.CharSequence field_low_price;
    private java.lang.CharSequence field_high_price;
    private java.lang.CharSequence field_cumul_volume_echange;
    private java.lang.CharSequence field_last_traded_price;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public BourseData() {}

    /**
     * All-args constructor.
     * @param field_date_application The new value for field_date_application
     * @param field_closing_price The new value for field_closing_price
     * @param field_difference The new value for field_difference
     * @param field_var_veille The new value for field_var_veille
     * @param field_best_ask_size The new value for field_best_ask_size
     * @param field_transact_time The new value for field_transact_time
     * @param field_cours_cloture The new value for field_cours_cloture
     * @param field_cours_ajuste The new value for field_cours_ajuste
     * @param field_cumul_titres_echanges The new value for field_cumul_titres_echanges
     * @param field_best_bid_size The new value for field_best_bid_size
     * @param field_capitalisation The new value for field_capitalisation
     * @param field_opening_price The new value for field_opening_price
     * @param field_total_trades The new value for field_total_trades
     * @param field_cours_courant The new value for field_cours_courant
     * @param field_best_ask_price The new value for field_best_ask_price
     * @param sous_secteur The new value for sous_secteur
     * @param ticker The new value for ticker
     * @param field_instrument_var_year The new value for field_instrument_var_year
     * @param field_var_pto The new value for field_var_pto
     * @param field_last_traded_time The new value for field_last_traded_time
     * @param label The new value for label
     * @param field_best_bid_price The new value for field_best_bid_price
     * @param field_dynamic_reference_price The new value for field_dynamic_reference_price
     * @param field_static_reference_price The new value for field_static_reference_price
     * @param field_low_price The new value for field_low_price
     * @param field_high_price The new value for field_high_price
     * @param field_cumul_volume_echange The new value for field_cumul_volume_echange
     * @param field_last_traded_price The new value for field_last_traded_price
     */
    public BourseData(java.lang.CharSequence field_date_application, java.lang.CharSequence field_closing_price, java.lang.CharSequence field_difference, java.lang.CharSequence field_var_veille, java.lang.CharSequence field_best_ask_size, java.lang.CharSequence field_transact_time, java.lang.CharSequence field_cours_cloture, java.lang.CharSequence field_cours_ajuste, java.lang.CharSequence field_cumul_titres_echanges, java.lang.CharSequence field_best_bid_size, java.lang.CharSequence field_capitalisation, java.lang.CharSequence field_opening_price, java.lang.CharSequence field_total_trades, java.lang.CharSequence field_cours_courant, java.lang.CharSequence field_best_ask_price, java.lang.CharSequence sous_secteur, java.lang.CharSequence ticker, java.lang.CharSequence field_instrument_var_year, java.lang.CharSequence field_var_pto, java.lang.CharSequence field_last_traded_time, java.lang.CharSequence label, java.lang.CharSequence field_best_bid_price, java.lang.CharSequence field_dynamic_reference_price, java.lang.CharSequence field_static_reference_price, java.lang.CharSequence field_low_price, java.lang.CharSequence field_high_price, java.lang.CharSequence field_cumul_volume_echange, java.lang.CharSequence field_last_traded_price) {
        this.field_date_application = field_date_application;
        this.field_closing_price = field_closing_price;
        this.field_difference = field_difference;
        this.field_var_veille = field_var_veille;
        this.field_best_ask_size = field_best_ask_size;
        this.field_transact_time = field_transact_time;
        this.field_cours_cloture = field_cours_cloture;
        this.field_cours_ajuste = field_cours_ajuste;
        this.field_cumul_titres_echanges = field_cumul_titres_echanges;
        this.field_best_bid_size = field_best_bid_size;
        this.field_capitalisation = field_capitalisation;
        this.field_opening_price = field_opening_price;
        this.field_total_trades = field_total_trades;
        this.field_cours_courant = field_cours_courant;
        this.field_best_ask_price = field_best_ask_price;
        this.sous_secteur = sous_secteur;
        this.ticker = ticker;
        this.field_instrument_var_year = field_instrument_var_year;
        this.field_var_pto = field_var_pto;
        this.field_last_traded_time = field_last_traded_time;
        this.label = label;
        this.field_best_bid_price = field_best_bid_price;
        this.field_dynamic_reference_price = field_dynamic_reference_price;
        this.field_static_reference_price = field_static_reference_price;
        this.field_low_price = field_low_price;
        this.field_high_price = field_high_price;
        this.field_cumul_volume_echange = field_cumul_volume_echange;
        this.field_last_traded_price = field_last_traded_price;
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

    @Override
    public org.apache.avro.Schema getSchema() { return SCHEMA$; }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0: return field_date_application;
            case 1: return field_closing_price;
            case 2: return field_difference;
            case 3: return field_var_veille;
            case 4: return field_best_ask_size;
            case 5: return field_transact_time;
            case 6: return field_cours_cloture;
            case 7: return field_cours_ajuste;
            case 8: return field_cumul_titres_echanges;
            case 9: return field_best_bid_size;
            case 10: return field_capitalisation;
            case 11: return field_opening_price;
            case 12: return field_total_trades;
            case 13: return field_cours_courant;
            case 14: return field_best_ask_price;
            case 15: return sous_secteur;
            case 16: return ticker;
            case 17: return field_instrument_var_year;
            case 18: return field_var_pto;
            case 19: return field_last_traded_time;
            case 20: return label;
            case 21: return field_best_bid_price;
            case 22: return field_dynamic_reference_price;
            case 23: return field_static_reference_price;
            case 24: return field_low_price;
            case 25: return field_high_price;
            case 26: return field_cumul_volume_echange;
            case 27: return field_last_traded_price;
            default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value="unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0: field_date_application = (java.lang.CharSequence)value$; break;
            case 1: field_closing_price = (java.lang.CharSequence)value$; break;
            case 2: field_difference = (java.lang.CharSequence)value$; break;
            case 3: field_var_veille = (java.lang.CharSequence)value$; break;
            case 4: field_best_ask_size = (java.lang.CharSequence)value$; break;
            case 5: field_transact_time = (java.lang.CharSequence)value$; break;
            case 6: field_cours_cloture = (java.lang.CharSequence)value$; break;
            case 7: field_cours_ajuste = (java.lang.CharSequence)value$; break;
            case 8: field_cumul_titres_echanges = (java.lang.CharSequence)value$; break;
            case 9: field_best_bid_size = (java.lang.CharSequence)value$; break;
            case 10: field_capitalisation = (java.lang.CharSequence)value$; break;
            case 11: field_opening_price = (java.lang.CharSequence)value$; break;
            case 12: field_total_trades = (java.lang.CharSequence)value$; break;
            case 13: field_cours_courant = (java.lang.CharSequence)value$; break;
            case 14: field_best_ask_price = (java.lang.CharSequence)value$; break;
            case 15: sous_secteur = (java.lang.CharSequence)value$; break;
            case 16: ticker = (java.lang.CharSequence)value$; break;
            case 17: field_instrument_var_year = (java.lang.CharSequence)value$; break;
            case 18: field_var_pto = (java.lang.CharSequence)value$; break;
            case 19: field_last_traded_time = (java.lang.CharSequence)value$; break;
            case 20: label = (java.lang.CharSequence)value$; break;
            case 21: field_best_bid_price = (java.lang.CharSequence)value$; break;
            case 22: field_dynamic_reference_price = (java.lang.CharSequence)value$; break;
            case 23: field_static_reference_price = (java.lang.CharSequence)value$; break;
            case 24: field_low_price = (java.lang.CharSequence)value$; break;
            case 25: field_high_price = (java.lang.CharSequence)value$; break;
            case 26: field_cumul_volume_echange = (java.lang.CharSequence)value$; break;
            case 27: field_last_traded_price = (java.lang.CharSequence)value$; break;
            default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'field_date_application' field.
     * @return The value of the 'field_date_application' field.
     */
    public java.lang.CharSequence getFieldDateApplication() {
        return field_date_application;
    }


    /**
     * Sets the value of the 'field_date_application' field.
     * @param value the value to set.
     */
    public void setFieldDateApplication(java.lang.CharSequence value) {
        this.field_date_application = value;
    }

    /**
     * Gets the value of the 'field_closing_price' field.
     * @return The value of the 'field_closing_price' field.
     */
    public java.lang.CharSequence getFieldClosingPrice() {
        return field_closing_price;
    }


    /**
     * Sets the value of the 'field_closing_price' field.
     * @param value the value to set.
     */
    public void setFieldClosingPrice(java.lang.CharSequence value) {
        this.field_closing_price = value;
    }

    /**
     * Gets the value of the 'field_difference' field.
     * @return The value of the 'field_difference' field.
     */
    public java.lang.CharSequence getFieldDifference() {
        return field_difference;
    }


    /**
     * Sets the value of the 'field_difference' field.
     * @param value the value to set.
     */
    public void setFieldDifference(java.lang.CharSequence value) {
        this.field_difference = value;
    }

    /**
     * Gets the value of the 'field_var_veille' field.
     * @return The value of the 'field_var_veille' field.
     */
    public java.lang.CharSequence getFieldVarVeille() {
        return field_var_veille;
    }


    /**
     * Sets the value of the 'field_var_veille' field.
     * @param value the value to set.
     */
    public void setFieldVarVeille(java.lang.CharSequence value) {
        this.field_var_veille = value;
    }

    /**
     * Gets the value of the 'field_best_ask_size' field.
     * @return The value of the 'field_best_ask_size' field.
     */
    public java.lang.CharSequence getFieldBestAskSize() {
        return field_best_ask_size;
    }


    /**
     * Sets the value of the 'field_best_ask_size' field.
     * @param value the value to set.
     */
    public void setFieldBestAskSize(java.lang.CharSequence value) {
        this.field_best_ask_size = value;
    }

    /**
     * Gets the value of the 'field_transact_time' field.
     * @return The value of the 'field_transact_time' field.
     */
    public java.lang.CharSequence getFieldTransactTime() {
        return field_transact_time;
    }


    /**
     * Sets the value of the 'field_transact_time' field.
     * @param value the value to set.
     */
    public void setFieldTransactTime(java.lang.CharSequence value) {
        this.field_transact_time = value;
    }

    /**
     * Gets the value of the 'field_cours_cloture' field.
     * @return The value of the 'field_cours_cloture' field.
     */
    public java.lang.CharSequence getFieldCoursCloture() {
        return field_cours_cloture;
    }


    /**
     * Sets the value of the 'field_cours_cloture' field.
     * @param value the value to set.
     */
    public void setFieldCoursCloture(java.lang.CharSequence value) {
        this.field_cours_cloture = value;
    }

    /**
     * Gets the value of the 'field_cours_ajuste' field.
     * @return The value of the 'field_cours_ajuste' field.
     */
    public java.lang.CharSequence getFieldCoursAjuste() {
        return field_cours_ajuste;
    }


    /**
     * Sets the value of the 'field_cours_ajuste' field.
     * @param value the value to set.
     */
    public void setFieldCoursAjuste(java.lang.CharSequence value) {
        this.field_cours_ajuste = value;
    }

    /**
     * Gets the value of the 'field_cumul_titres_echanges' field.
     * @return The value of the 'field_cumul_titres_echanges' field.
     */
    public java.lang.CharSequence getFieldCumulTitresEchanges() {
        return field_cumul_titres_echanges;
    }


    /**
     * Sets the value of the 'field_cumul_titres_echanges' field.
     * @param value the value to set.
     */
    public void setFieldCumulTitresEchanges(java.lang.CharSequence value) {
        this.field_cumul_titres_echanges = value;
    }

    /**
     * Gets the value of the 'field_best_bid_size' field.
     * @return The value of the 'field_best_bid_size' field.
     */
    public java.lang.CharSequence getFieldBestBidSize() {
        return field_best_bid_size;
    }


    /**
     * Sets the value of the 'field_best_bid_size' field.
     * @param value the value to set.
     */
    public void setFieldBestBidSize(java.lang.CharSequence value) {
        this.field_best_bid_size = value;
    }

    /**
     * Gets the value of the 'field_capitalisation' field.
     * @return The value of the 'field_capitalisation' field.
     */
    public java.lang.CharSequence getFieldCapitalisation() {
        return field_capitalisation;
    }


    /**
     * Sets the value of the 'field_capitalisation' field.
     * @param value the value to set.
     */
    public void setFieldCapitalisation(java.lang.CharSequence value) {
        this.field_capitalisation = value;
    }

    /**
     * Gets the value of the 'field_opening_price' field.
     * @return The value of the 'field_opening_price' field.
     */
    public java.lang.CharSequence getFieldOpeningPrice() {
        return field_opening_price;
    }


    /**
     * Sets the value of the 'field_opening_price' field.
     * @param value the value to set.
     */
    public void setFieldOpeningPrice(java.lang.CharSequence value) {
        this.field_opening_price = value;
    }

    /**
     * Gets the value of the 'field_total_trades' field.
     * @return The value of the 'field_total_trades' field.
     */
    public java.lang.CharSequence getFieldTotalTrades() {
        return field_total_trades;
    }


    /**
     * Sets the value of the 'field_total_trades' field.
     * @param value the value to set.
     */
    public void setFieldTotalTrades(java.lang.CharSequence value) {
        this.field_total_trades = value;
    }

    /**
     * Gets the value of the 'field_cours_courant' field.
     * @return The value of the 'field_cours_courant' field.
     */
    public java.lang.CharSequence getFieldCoursCourant() {
        return field_cours_courant;
    }


    /**
     * Sets the value of the 'field_cours_courant' field.
     * @param value the value to set.
     */
    public void setFieldCoursCourant(java.lang.CharSequence value) {
        this.field_cours_courant = value;
    }

    /**
     * Gets the value of the 'field_best_ask_price' field.
     * @return The value of the 'field_best_ask_price' field.
     */
    public java.lang.CharSequence getFieldBestAskPrice() {
        return field_best_ask_price;
    }


    /**
     * Sets the value of the 'field_best_ask_price' field.
     * @param value the value to set.
     */
    public void setFieldBestAskPrice(java.lang.CharSequence value) {
        this.field_best_ask_price = value;
    }

    /**
     * Gets the value of the 'sous_secteur' field.
     * @return The value of the 'sous_secteur' field.
     */
    public java.lang.CharSequence getSousSecteur() {
        return sous_secteur;
    }


    /**
     * Sets the value of the 'sous_secteur' field.
     * @param value the value to set.
     */
    public void setSousSecteur(java.lang.CharSequence value) {
        this.sous_secteur = value;
    }

    /**
     * Gets the value of the 'ticker' field.
     * @return The value of the 'ticker' field.
     */
    public java.lang.CharSequence getTicker() {
        return ticker;
    }


    /**
     * Sets the value of the 'ticker' field.
     * @param value the value to set.
     */
    public void setTicker(java.lang.CharSequence value) {
        this.ticker = value;
    }

    /**
     * Gets the value of the 'field_instrument_var_year' field.
     * @return The value of the 'field_instrument_var_year' field.
     */
    public java.lang.CharSequence getFieldInstrumentVarYear() {
        return field_instrument_var_year;
    }


    /**
     * Sets the value of the 'field_instrument_var_year' field.
     * @param value the value to set.
     */
    public void setFieldInstrumentVarYear(java.lang.CharSequence value) {
        this.field_instrument_var_year = value;
    }

    /**
     * Gets the value of the 'field_var_pto' field.
     * @return The value of the 'field_var_pto' field.
     */
    public java.lang.CharSequence getFieldVarPto() {
        return field_var_pto;
    }


    /**
     * Sets the value of the 'field_var_pto' field.
     * @param value the value to set.
     */
    public void setFieldVarPto(java.lang.CharSequence value) {
        this.field_var_pto = value;
    }

    /**
     * Gets the value of the 'field_last_traded_time' field.
     * @return The value of the 'field_last_traded_time' field.
     */
    public java.lang.CharSequence getFieldLastTradedTime() {
        return field_last_traded_time;
    }


    /**
     * Sets the value of the 'field_last_traded_time' field.
     * @param value the value to set.
     */
    public void setFieldLastTradedTime(java.lang.CharSequence value) {
        this.field_last_traded_time = value;
    }

    /**
     * Gets the value of the 'label' field.
     * @return The value of the 'label' field.
     */
    public java.lang.CharSequence getLabel() {
        return label;
    }


    /**
     * Sets the value of the 'label' field.
     * @param value the value to set.
     */
    public void setLabel(java.lang.CharSequence value) {
        this.label = value;
    }

    /**
     * Gets the value of the 'field_best_bid_price' field.
     * @return The value of the 'field_best_bid_price' field.
     */
    public java.lang.CharSequence getFieldBestBidPrice() {
        return field_best_bid_price;
    }


    /**
     * Sets the value of the 'field_best_bid_price' field.
     * @param value the value to set.
     */
    public void setFieldBestBidPrice(java.lang.CharSequence value) {
        this.field_best_bid_price = value;
    }

    /**
     * Gets the value of the 'field_dynamic_reference_price' field.
     * @return The value of the 'field_dynamic_reference_price' field.
     */
    public java.lang.CharSequence getFieldDynamicReferencePrice() {
        return field_dynamic_reference_price;
    }


    /**
     * Sets the value of the 'field_dynamic_reference_price' field.
     * @param value the value to set.
     */
    public void setFieldDynamicReferencePrice(java.lang.CharSequence value) {
        this.field_dynamic_reference_price = value;
    }

    /**
     * Gets the value of the 'field_static_reference_price' field.
     * @return The value of the 'field_static_reference_price' field.
     */
    public java.lang.CharSequence getFieldStaticReferencePrice() {
        return field_static_reference_price;
    }


    /**
     * Sets the value of the 'field_static_reference_price' field.
     * @param value the value to set.
     */
    public void setFieldStaticReferencePrice(java.lang.CharSequence value) {
        this.field_static_reference_price = value;
    }

    /**
     * Gets the value of the 'field_low_price' field.
     * @return The value of the 'field_low_price' field.
     */
    public java.lang.CharSequence getFieldLowPrice() {
        return field_low_price;
    }


    /**
     * Sets the value of the 'field_low_price' field.
     * @param value the value to set.
     */
    public void setFieldLowPrice(java.lang.CharSequence value) {
        this.field_low_price = value;
    }

    /**
     * Gets the value of the 'field_high_price' field.
     * @return The value of the 'field_high_price' field.
     */
    public java.lang.CharSequence getFieldHighPrice() {
        return field_high_price;
    }


    /**
     * Sets the value of the 'field_high_price' field.
     * @param value the value to set.
     */
    public void setFieldHighPrice(java.lang.CharSequence value) {
        this.field_high_price = value;
    }

    /**
     * Gets the value of the 'field_cumul_volume_echange' field.
     * @return The value of the 'field_cumul_volume_echange' field.
     */
    public java.lang.CharSequence getFieldCumulVolumeEchange() {
        return field_cumul_volume_echange;
    }


    /**
     * Sets the value of the 'field_cumul_volume_echange' field.
     * @param value the value to set.
     */
    public void setFieldCumulVolumeEchange(java.lang.CharSequence value) {
        this.field_cumul_volume_echange = value;
    }

    /**
     * Gets the value of the 'field_last_traded_price' field.
     * @return The value of the 'field_last_traded_price' field.
     */
    public java.lang.CharSequence getFieldLastTradedPrice() {
        return field_last_traded_price;
    }


    /**
     * Sets the value of the 'field_last_traded_price' field.
     * @param value the value to set.
     */
    public void setFieldLastTradedPrice(java.lang.CharSequence value) {
        this.field_last_traded_price = value;
    }

    /**
     * Creates a new BourseData RecordBuilder.
     * @return A new BourseData RecordBuilder
     */
    public static com.popupd.util.BourseData.Builder newBuilder() {
        return new com.popupd.util.BourseData.Builder();
    }

    /**
     * Creates a new BourseData RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new BourseData RecordBuilder
     */
    public static com.popupd.util.BourseData.Builder newBuilder(com.popupd.util.BourseData.Builder other) {
        if (other == null) {
            return new com.popupd.util.BourseData.Builder();
        } else {
            return new com.popupd.util.BourseData.Builder(other);
        }
    }

    /**
     * Creates a new BourseData RecordBuilder by copying an existing BourseData instance.
     * @param other The existing instance to copy.
     * @return A new BourseData RecordBuilder
     */
    public static com.popupd.util.BourseData.Builder newBuilder(com.popupd.util.BourseData other) {
        if (other == null) {
            return new com.popupd.util.BourseData.Builder();
        } else {
            return new com.popupd.util.BourseData.Builder(other);
        }
    }

    /**
     * RecordBuilder for BourseData instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BourseData>
            implements org.apache.avro.data.RecordBuilder<BourseData> {

        private java.lang.CharSequence field_date_application;
        private java.lang.CharSequence field_closing_price;
        private java.lang.CharSequence field_difference;
        private java.lang.CharSequence field_var_veille;
        private java.lang.CharSequence field_best_ask_size;
        private java.lang.CharSequence field_transact_time;
        private java.lang.CharSequence field_cours_cloture;
        private java.lang.CharSequence field_cours_ajuste;
        private java.lang.CharSequence field_cumul_titres_echanges;
        private java.lang.CharSequence field_best_bid_size;
        private java.lang.CharSequence field_capitalisation;
        private java.lang.CharSequence field_opening_price;
        private java.lang.CharSequence field_total_trades;
        private java.lang.CharSequence field_cours_courant;
        private java.lang.CharSequence field_best_ask_price;
        private java.lang.CharSequence sous_secteur;
        private java.lang.CharSequence ticker;
        private java.lang.CharSequence field_instrument_var_year;
        private java.lang.CharSequence field_var_pto;
        private java.lang.CharSequence field_last_traded_time;
        private java.lang.CharSequence label;
        private java.lang.CharSequence field_best_bid_price;
        private java.lang.CharSequence field_dynamic_reference_price;
        private java.lang.CharSequence field_static_reference_price;
        private java.lang.CharSequence field_low_price;
        private java.lang.CharSequence field_high_price;
        private java.lang.CharSequence field_cumul_volume_echange;
        private java.lang.CharSequence field_last_traded_price;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.popupd.util.BourseData.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.field_date_application)) {
                this.field_date_application = data().deepCopy(fields()[0].schema(), other.field_date_application);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.field_closing_price)) {
                this.field_closing_price = data().deepCopy(fields()[1].schema(), other.field_closing_price);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.field_difference)) {
                this.field_difference = data().deepCopy(fields()[2].schema(), other.field_difference);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
            if (isValidValue(fields()[3], other.field_var_veille)) {
                this.field_var_veille = data().deepCopy(fields()[3].schema(), other.field_var_veille);
                fieldSetFlags()[3] = other.fieldSetFlags()[3];
            }
            if (isValidValue(fields()[4], other.field_best_ask_size)) {
                this.field_best_ask_size = data().deepCopy(fields()[4].schema(), other.field_best_ask_size);
                fieldSetFlags()[4] = other.fieldSetFlags()[4];
            }
            if (isValidValue(fields()[5], other.field_transact_time)) {
                this.field_transact_time = data().deepCopy(fields()[5].schema(), other.field_transact_time);
                fieldSetFlags()[5] = other.fieldSetFlags()[5];
            }
            if (isValidValue(fields()[6], other.field_cours_cloture)) {
                this.field_cours_cloture = data().deepCopy(fields()[6].schema(), other.field_cours_cloture);
                fieldSetFlags()[6] = other.fieldSetFlags()[6];
            }
            if (isValidValue(fields()[7], other.field_cours_ajuste)) {
                this.field_cours_ajuste = data().deepCopy(fields()[7].schema(), other.field_cours_ajuste);
                fieldSetFlags()[7] = other.fieldSetFlags()[7];
            }
            if (isValidValue(fields()[8], other.field_cumul_titres_echanges)) {
                this.field_cumul_titres_echanges = data().deepCopy(fields()[8].schema(), other.field_cumul_titres_echanges);
                fieldSetFlags()[8] = other.fieldSetFlags()[8];
            }
            if (isValidValue(fields()[9], other.field_best_bid_size)) {
                this.field_best_bid_size = data().deepCopy(fields()[9].schema(), other.field_best_bid_size);
                fieldSetFlags()[9] = other.fieldSetFlags()[9];
            }
            if (isValidValue(fields()[10], other.field_capitalisation)) {
                this.field_capitalisation = data().deepCopy(fields()[10].schema(), other.field_capitalisation);
                fieldSetFlags()[10] = other.fieldSetFlags()[10];
            }
            if (isValidValue(fields()[11], other.field_opening_price)) {
                this.field_opening_price = data().deepCopy(fields()[11].schema(), other.field_opening_price);
                fieldSetFlags()[11] = other.fieldSetFlags()[11];
            }
            if (isValidValue(fields()[12], other.field_total_trades)) {
                this.field_total_trades = data().deepCopy(fields()[12].schema(), other.field_total_trades);
                fieldSetFlags()[12] = other.fieldSetFlags()[12];
            }
            if (isValidValue(fields()[13], other.field_cours_courant)) {
                this.field_cours_courant = data().deepCopy(fields()[13].schema(), other.field_cours_courant);
                fieldSetFlags()[13] = other.fieldSetFlags()[13];
            }
            if (isValidValue(fields()[14], other.field_best_ask_price)) {
                this.field_best_ask_price = data().deepCopy(fields()[14].schema(), other.field_best_ask_price);
                fieldSetFlags()[14] = other.fieldSetFlags()[14];
            }
            if (isValidValue(fields()[15], other.sous_secteur)) {
                this.sous_secteur = data().deepCopy(fields()[15].schema(), other.sous_secteur);
                fieldSetFlags()[15] = other.fieldSetFlags()[15];
            }
            if (isValidValue(fields()[16], other.ticker)) {
                this.ticker = data().deepCopy(fields()[16].schema(), other.ticker);
                fieldSetFlags()[16] = other.fieldSetFlags()[16];
            }
            if (isValidValue(fields()[17], other.field_instrument_var_year)) {
                this.field_instrument_var_year = data().deepCopy(fields()[17].schema(), other.field_instrument_var_year);
                fieldSetFlags()[17] = other.fieldSetFlags()[17];
            }
            if (isValidValue(fields()[18], other.field_var_pto)) {
                this.field_var_pto = data().deepCopy(fields()[18].schema(), other.field_var_pto);
                fieldSetFlags()[18] = other.fieldSetFlags()[18];
            }
            if (isValidValue(fields()[19], other.field_last_traded_time)) {
                this.field_last_traded_time = data().deepCopy(fields()[19].schema(), other.field_last_traded_time);
                fieldSetFlags()[19] = other.fieldSetFlags()[19];
            }
            if (isValidValue(fields()[20], other.label)) {
                this.label = data().deepCopy(fields()[20].schema(), other.label);
                fieldSetFlags()[20] = other.fieldSetFlags()[20];
            }
            if (isValidValue(fields()[21], other.field_best_bid_price)) {
                this.field_best_bid_price = data().deepCopy(fields()[21].schema(), other.field_best_bid_price);
                fieldSetFlags()[21] = other.fieldSetFlags()[21];
            }
            if (isValidValue(fields()[22], other.field_dynamic_reference_price)) {
                this.field_dynamic_reference_price = data().deepCopy(fields()[22].schema(), other.field_dynamic_reference_price);
                fieldSetFlags()[22] = other.fieldSetFlags()[22];
            }
            if (isValidValue(fields()[23], other.field_static_reference_price)) {
                this.field_static_reference_price = data().deepCopy(fields()[23].schema(), other.field_static_reference_price);
                fieldSetFlags()[23] = other.fieldSetFlags()[23];
            }
            if (isValidValue(fields()[24], other.field_low_price)) {
                this.field_low_price = data().deepCopy(fields()[24].schema(), other.field_low_price);
                fieldSetFlags()[24] = other.fieldSetFlags()[24];
            }
            if (isValidValue(fields()[25], other.field_high_price)) {
                this.field_high_price = data().deepCopy(fields()[25].schema(), other.field_high_price);
                fieldSetFlags()[25] = other.fieldSetFlags()[25];
            }
            if (isValidValue(fields()[26], other.field_cumul_volume_echange)) {
                this.field_cumul_volume_echange = data().deepCopy(fields()[26].schema(), other.field_cumul_volume_echange);
                fieldSetFlags()[26] = other.fieldSetFlags()[26];
            }
            if (isValidValue(fields()[27], other.field_last_traded_price)) {
                this.field_last_traded_price = data().deepCopy(fields()[27].schema(), other.field_last_traded_price);
                fieldSetFlags()[27] = other.fieldSetFlags()[27];
            }
        }

        /**
         * Creates a Builder by copying an existing BourseData instance
         * @param other The existing instance to copy.
         */
        private Builder(com.popupd.util.BourseData other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.field_date_application)) {
                this.field_date_application = data().deepCopy(fields()[0].schema(), other.field_date_application);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.field_closing_price)) {
                this.field_closing_price = data().deepCopy(fields()[1].schema(), other.field_closing_price);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.field_difference)) {
                this.field_difference = data().deepCopy(fields()[2].schema(), other.field_difference);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.field_var_veille)) {
                this.field_var_veille = data().deepCopy(fields()[3].schema(), other.field_var_veille);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.field_best_ask_size)) {
                this.field_best_ask_size = data().deepCopy(fields()[4].schema(), other.field_best_ask_size);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.field_transact_time)) {
                this.field_transact_time = data().deepCopy(fields()[5].schema(), other.field_transact_time);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.field_cours_cloture)) {
                this.field_cours_cloture = data().deepCopy(fields()[6].schema(), other.field_cours_cloture);
                fieldSetFlags()[6] = true;
            }
            if (isValidValue(fields()[7], other.field_cours_ajuste)) {
                this.field_cours_ajuste = data().deepCopy(fields()[7].schema(), other.field_cours_ajuste);
                fieldSetFlags()[7] = true;
            }
            if (isValidValue(fields()[8], other.field_cumul_titres_echanges)) {
                this.field_cumul_titres_echanges = data().deepCopy(fields()[8].schema(), other.field_cumul_titres_echanges);
                fieldSetFlags()[8] = true;
            }
            if (isValidValue(fields()[9], other.field_best_bid_size)) {
                this.field_best_bid_size = data().deepCopy(fields()[9].schema(), other.field_best_bid_size);
                fieldSetFlags()[9] = true;
            }
            if (isValidValue(fields()[10], other.field_capitalisation)) {
                this.field_capitalisation = data().deepCopy(fields()[10].schema(), other.field_capitalisation);
                fieldSetFlags()[10] = true;
            }
            if (isValidValue(fields()[11], other.field_opening_price)) {
                this.field_opening_price = data().deepCopy(fields()[11].schema(), other.field_opening_price);
                fieldSetFlags()[11] = true;
            }
            if (isValidValue(fields()[12], other.field_total_trades)) {
                this.field_total_trades = data().deepCopy(fields()[12].schema(), other.field_total_trades);
                fieldSetFlags()[12] = true;
            }
            if (isValidValue(fields()[13], other.field_cours_courant)) {
                this.field_cours_courant = data().deepCopy(fields()[13].schema(), other.field_cours_courant);
                fieldSetFlags()[13] = true;
            }
            if (isValidValue(fields()[14], other.field_best_ask_price)) {
                this.field_best_ask_price = data().deepCopy(fields()[14].schema(), other.field_best_ask_price);
                fieldSetFlags()[14] = true;
            }
            if (isValidValue(fields()[15], other.sous_secteur)) {
                this.sous_secteur = data().deepCopy(fields()[15].schema(), other.sous_secteur);
                fieldSetFlags()[15] = true;
            }
            if (isValidValue(fields()[16], other.ticker)) {
                this.ticker = data().deepCopy(fields()[16].schema(), other.ticker);
                fieldSetFlags()[16] = true;
            }
            if (isValidValue(fields()[17], other.field_instrument_var_year)) {
                this.field_instrument_var_year = data().deepCopy(fields()[17].schema(), other.field_instrument_var_year);
                fieldSetFlags()[17] = true;
            }
            if (isValidValue(fields()[18], other.field_var_pto)) {
                this.field_var_pto = data().deepCopy(fields()[18].schema(), other.field_var_pto);
                fieldSetFlags()[18] = true;
            }
            if (isValidValue(fields()[19], other.field_last_traded_time)) {
                this.field_last_traded_time = data().deepCopy(fields()[19].schema(), other.field_last_traded_time);
                fieldSetFlags()[19] = true;
            }
            if (isValidValue(fields()[20], other.label)) {
                this.label = data().deepCopy(fields()[20].schema(), other.label);
                fieldSetFlags()[20] = true;
            }
            if (isValidValue(fields()[21], other.field_best_bid_price)) {
                this.field_best_bid_price = data().deepCopy(fields()[21].schema(), other.field_best_bid_price);
                fieldSetFlags()[21] = true;
            }
            if (isValidValue(fields()[22], other.field_dynamic_reference_price)) {
                this.field_dynamic_reference_price = data().deepCopy(fields()[22].schema(), other.field_dynamic_reference_price);
                fieldSetFlags()[22] = true;
            }
            if (isValidValue(fields()[23], other.field_static_reference_price)) {
                this.field_static_reference_price = data().deepCopy(fields()[23].schema(), other.field_static_reference_price);
                fieldSetFlags()[23] = true;
            }
            if (isValidValue(fields()[24], other.field_low_price)) {
                this.field_low_price = data().deepCopy(fields()[24].schema(), other.field_low_price);
                fieldSetFlags()[24] = true;
            }
            if (isValidValue(fields()[25], other.field_high_price)) {
                this.field_high_price = data().deepCopy(fields()[25].schema(), other.field_high_price);
                fieldSetFlags()[25] = true;
            }
            if (isValidValue(fields()[26], other.field_cumul_volume_echange)) {
                this.field_cumul_volume_echange = data().deepCopy(fields()[26].schema(), other.field_cumul_volume_echange);
                fieldSetFlags()[26] = true;
            }
            if (isValidValue(fields()[27], other.field_last_traded_price)) {
                this.field_last_traded_price = data().deepCopy(fields()[27].schema(), other.field_last_traded_price);
                fieldSetFlags()[27] = true;
            }
        }

        /**
         * Gets the value of the 'field_date_application' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldDateApplication() {
            return field_date_application;
        }


        /**
         * Sets the value of the 'field_date_application' field.
         * @param value The value of 'field_date_application'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldDateApplication(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.field_date_application = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'field_date_application' field has been set.
         * @return True if the 'field_date_application' field has been set, false otherwise.
         */
        public boolean hasFieldDateApplication() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'field_date_application' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldDateApplication() {
            field_date_application = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_closing_price' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldClosingPrice() {
            return field_closing_price;
        }


        /**
         * Sets the value of the 'field_closing_price' field.
         * @param value The value of 'field_closing_price'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldClosingPrice(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.field_closing_price = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'field_closing_price' field has been set.
         * @return True if the 'field_closing_price' field has been set, false otherwise.
         */
        public boolean hasFieldClosingPrice() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'field_closing_price' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldClosingPrice() {
            field_closing_price = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_difference' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldDifference() {
            return field_difference;
        }


        /**
         * Sets the value of the 'field_difference' field.
         * @param value The value of 'field_difference'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldDifference(java.lang.CharSequence value) {
            validate(fields()[2], value);
            this.field_difference = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'field_difference' field has been set.
         * @return True if the 'field_difference' field has been set, false otherwise.
         */
        public boolean hasFieldDifference() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'field_difference' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldDifference() {
            field_difference = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_var_veille' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldVarVeille() {
            return field_var_veille;
        }


        /**
         * Sets the value of the 'field_var_veille' field.
         * @param value The value of 'field_var_veille'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldVarVeille(java.lang.CharSequence value) {
            validate(fields()[3], value);
            this.field_var_veille = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'field_var_veille' field has been set.
         * @return True if the 'field_var_veille' field has been set, false otherwise.
         */
        public boolean hasFieldVarVeille() {
            return fieldSetFlags()[3];
        }


        /**
         * Clears the value of the 'field_var_veille' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldVarVeille() {
            field_var_veille = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_best_ask_size' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldBestAskSize() {
            return field_best_ask_size;
        }


        /**
         * Sets the value of the 'field_best_ask_size' field.
         * @param value The value of 'field_best_ask_size'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldBestAskSize(java.lang.CharSequence value) {
            validate(fields()[4], value);
            this.field_best_ask_size = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'field_best_ask_size' field has been set.
         * @return True if the 'field_best_ask_size' field has been set, false otherwise.
         */
        public boolean hasFieldBestAskSize() {
            return fieldSetFlags()[4];
        }


        /**
         * Clears the value of the 'field_best_ask_size' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldBestAskSize() {
            field_best_ask_size = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_transact_time' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldTransactTime() {
            return field_transact_time;
        }


        /**
         * Sets the value of the 'field_transact_time' field.
         * @param value The value of 'field_transact_time'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldTransactTime(java.lang.CharSequence value) {
            validate(fields()[5], value);
            this.field_transact_time = value;
            fieldSetFlags()[5] = true;
            return this;
        }

        /**
         * Checks whether the 'field_transact_time' field has been set.
         * @return True if the 'field_transact_time' field has been set, false otherwise.
         */
        public boolean hasFieldTransactTime() {
            return fieldSetFlags()[5];
        }


        /**
         * Clears the value of the 'field_transact_time' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldTransactTime() {
            field_transact_time = null;
            fieldSetFlags()[5] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_cours_cloture' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldCoursCloture() {
            return field_cours_cloture;
        }


        /**
         * Sets the value of the 'field_cours_cloture' field.
         * @param value The value of 'field_cours_cloture'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldCoursCloture(java.lang.CharSequence value) {
            validate(fields()[6], value);
            this.field_cours_cloture = value;
            fieldSetFlags()[6] = true;
            return this;
        }

        /**
         * Checks whether the 'field_cours_cloture' field has been set.
         * @return True if the 'field_cours_cloture' field has been set, false otherwise.
         */
        public boolean hasFieldCoursCloture() {
            return fieldSetFlags()[6];
        }


        /**
         * Clears the value of the 'field_cours_cloture' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldCoursCloture() {
            field_cours_cloture = null;
            fieldSetFlags()[6] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_cours_ajuste' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldCoursAjuste() {
            return field_cours_ajuste;
        }


        /**
         * Sets the value of the 'field_cours_ajuste' field.
         * @param value The value of 'field_cours_ajuste'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldCoursAjuste(java.lang.CharSequence value) {
            validate(fields()[7], value);
            this.field_cours_ajuste = value;
            fieldSetFlags()[7] = true;
            return this;
        }

        /**
         * Checks whether the 'field_cours_ajuste' field has been set.
         * @return True if the 'field_cours_ajuste' field has been set, false otherwise.
         */
        public boolean hasFieldCoursAjuste() {
            return fieldSetFlags()[7];
        }


        /**
         * Clears the value of the 'field_cours_ajuste' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldCoursAjuste() {
            field_cours_ajuste = null;
            fieldSetFlags()[7] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_cumul_titres_echanges' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldCumulTitresEchanges() {
            return field_cumul_titres_echanges;
        }


        /**
         * Sets the value of the 'field_cumul_titres_echanges' field.
         * @param value The value of 'field_cumul_titres_echanges'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldCumulTitresEchanges(java.lang.CharSequence value) {
            validate(fields()[8], value);
            this.field_cumul_titres_echanges = value;
            fieldSetFlags()[8] = true;
            return this;
        }

        /**
         * Checks whether the 'field_cumul_titres_echanges' field has been set.
         * @return True if the 'field_cumul_titres_echanges' field has been set, false otherwise.
         */
        public boolean hasFieldCumulTitresEchanges() {
            return fieldSetFlags()[8];
        }


        /**
         * Clears the value of the 'field_cumul_titres_echanges' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldCumulTitresEchanges() {
            field_cumul_titres_echanges = null;
            fieldSetFlags()[8] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_best_bid_size' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldBestBidSize() {
            return field_best_bid_size;
        }


        /**
         * Sets the value of the 'field_best_bid_size' field.
         * @param value The value of 'field_best_bid_size'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldBestBidSize(java.lang.CharSequence value) {
            validate(fields()[9], value);
            this.field_best_bid_size = value;
            fieldSetFlags()[9] = true;
            return this;
        }

        /**
         * Checks whether the 'field_best_bid_size' field has been set.
         * @return True if the 'field_best_bid_size' field has been set, false otherwise.
         */
        public boolean hasFieldBestBidSize() {
            return fieldSetFlags()[9];
        }


        /**
         * Clears the value of the 'field_best_bid_size' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldBestBidSize() {
            field_best_bid_size = null;
            fieldSetFlags()[9] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_capitalisation' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldCapitalisation() {
            return field_capitalisation;
        }


        /**
         * Sets the value of the 'field_capitalisation' field.
         * @param value The value of 'field_capitalisation'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldCapitalisation(java.lang.CharSequence value) {
            validate(fields()[10], value);
            this.field_capitalisation = value;
            fieldSetFlags()[10] = true;
            return this;
        }

        /**
         * Checks whether the 'field_capitalisation' field has been set.
         * @return True if the 'field_capitalisation' field has been set, false otherwise.
         */
        public boolean hasFieldCapitalisation() {
            return fieldSetFlags()[10];
        }


        /**
         * Clears the value of the 'field_capitalisation' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldCapitalisation() {
            field_capitalisation = null;
            fieldSetFlags()[10] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_opening_price' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldOpeningPrice() {
            return field_opening_price;
        }


        /**
         * Sets the value of the 'field_opening_price' field.
         * @param value The value of 'field_opening_price'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldOpeningPrice(java.lang.CharSequence value) {
            validate(fields()[11], value);
            this.field_opening_price = value;
            fieldSetFlags()[11] = true;
            return this;
        }

        /**
         * Checks whether the 'field_opening_price' field has been set.
         * @return True if the 'field_opening_price' field has been set, false otherwise.
         */
        public boolean hasFieldOpeningPrice() {
            return fieldSetFlags()[11];
        }


        /**
         * Clears the value of the 'field_opening_price' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldOpeningPrice() {
            field_opening_price = null;
            fieldSetFlags()[11] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_total_trades' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldTotalTrades() {
            return field_total_trades;
        }


        /**
         * Sets the value of the 'field_total_trades' field.
         * @param value The value of 'field_total_trades'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldTotalTrades(java.lang.CharSequence value) {
            validate(fields()[12], value);
            this.field_total_trades = value;
            fieldSetFlags()[12] = true;
            return this;
        }

        /**
         * Checks whether the 'field_total_trades' field has been set.
         * @return True if the 'field_total_trades' field has been set, false otherwise.
         */
        public boolean hasFieldTotalTrades() {
            return fieldSetFlags()[12];
        }


        /**
         * Clears the value of the 'field_total_trades' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldTotalTrades() {
            field_total_trades = null;
            fieldSetFlags()[12] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_cours_courant' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldCoursCourant() {
            return field_cours_courant;
        }


        /**
         * Sets the value of the 'field_cours_courant' field.
         * @param value The value of 'field_cours_courant'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldCoursCourant(java.lang.CharSequence value) {
            validate(fields()[13], value);
            this.field_cours_courant = value;
            fieldSetFlags()[13] = true;
            return this;
        }

        /**
         * Checks whether the 'field_cours_courant' field has been set.
         * @return True if the 'field_cours_courant' field has been set, false otherwise.
         */
        public boolean hasFieldCoursCourant() {
            return fieldSetFlags()[13];
        }


        /**
         * Clears the value of the 'field_cours_courant' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldCoursCourant() {
            field_cours_courant = null;
            fieldSetFlags()[13] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_best_ask_price' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldBestAskPrice() {
            return field_best_ask_price;
        }


        /**
         * Sets the value of the 'field_best_ask_price' field.
         * @param value The value of 'field_best_ask_price'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldBestAskPrice(java.lang.CharSequence value) {
            validate(fields()[14], value);
            this.field_best_ask_price = value;
            fieldSetFlags()[14] = true;
            return this;
        }

        /**
         * Checks whether the 'field_best_ask_price' field has been set.
         * @return True if the 'field_best_ask_price' field has been set, false otherwise.
         */
        public boolean hasFieldBestAskPrice() {
            return fieldSetFlags()[14];
        }


        /**
         * Clears the value of the 'field_best_ask_price' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldBestAskPrice() {
            field_best_ask_price = null;
            fieldSetFlags()[14] = false;
            return this;
        }

        /**
         * Gets the value of the 'sous_secteur' field.
         * @return The value.
         */
        public java.lang.CharSequence getSousSecteur() {
            return sous_secteur;
        }


        /**
         * Sets the value of the 'sous_secteur' field.
         * @param value The value of 'sous_secteur'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setSousSecteur(java.lang.CharSequence value) {
            validate(fields()[15], value);
            this.sous_secteur = value;
            fieldSetFlags()[15] = true;
            return this;
        }

        /**
         * Checks whether the 'sous_secteur' field has been set.
         * @return True if the 'sous_secteur' field has been set, false otherwise.
         */
        public boolean hasSousSecteur() {
            return fieldSetFlags()[15];
        }


        /**
         * Clears the value of the 'sous_secteur' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearSousSecteur() {
            sous_secteur = null;
            fieldSetFlags()[15] = false;
            return this;
        }

        /**
         * Gets the value of the 'ticker' field.
         * @return The value.
         */
        public java.lang.CharSequence getTicker() {
            return ticker;
        }


        /**
         * Sets the value of the 'ticker' field.
         * @param value The value of 'ticker'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setTicker(java.lang.CharSequence value) {
            validate(fields()[16], value);
            this.ticker = value;
            fieldSetFlags()[16] = true;
            return this;
        }

        /**
         * Checks whether the 'ticker' field has been set.
         * @return True if the 'ticker' field has been set, false otherwise.
         */
        public boolean hasTicker() {
            return fieldSetFlags()[16];
        }


        /**
         * Clears the value of the 'ticker' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearTicker() {
            ticker = null;
            fieldSetFlags()[16] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_instrument_var_year' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldInstrumentVarYear() {
            return field_instrument_var_year;
        }


        /**
         * Sets the value of the 'field_instrument_var_year' field.
         * @param value The value of 'field_instrument_var_year'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldInstrumentVarYear(java.lang.CharSequence value) {
            validate(fields()[17], value);
            this.field_instrument_var_year = value;
            fieldSetFlags()[17] = true;
            return this;
        }

        /**
         * Checks whether the 'field_instrument_var_year' field has been set.
         * @return True if the 'field_instrument_var_year' field has been set, false otherwise.
         */
        public boolean hasFieldInstrumentVarYear() {
            return fieldSetFlags()[17];
        }


        /**
         * Clears the value of the 'field_instrument_var_year' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldInstrumentVarYear() {
            field_instrument_var_year = null;
            fieldSetFlags()[17] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_var_pto' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldVarPto() {
            return field_var_pto;
        }


        /**
         * Sets the value of the 'field_var_pto' field.
         * @param value The value of 'field_var_pto'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldVarPto(java.lang.CharSequence value) {
            validate(fields()[18], value);
            this.field_var_pto = value;
            fieldSetFlags()[18] = true;
            return this;
        }

        /**
         * Checks whether the 'field_var_pto' field has been set.
         * @return True if the 'field_var_pto' field has been set, false otherwise.
         */
        public boolean hasFieldVarPto() {
            return fieldSetFlags()[18];
        }


        /**
         * Clears the value of the 'field_var_pto' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldVarPto() {
            field_var_pto = null;
            fieldSetFlags()[18] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_last_traded_time' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldLastTradedTime() {
            return field_last_traded_time;
        }


        /**
         * Sets the value of the 'field_last_traded_time' field.
         * @param value The value of 'field_last_traded_time'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldLastTradedTime(java.lang.CharSequence value) {
            validate(fields()[19], value);
            this.field_last_traded_time = value;
            fieldSetFlags()[19] = true;
            return this;
        }

        /**
         * Checks whether the 'field_last_traded_time' field has been set.
         * @return True if the 'field_last_traded_time' field has been set, false otherwise.
         */
        public boolean hasFieldLastTradedTime() {
            return fieldSetFlags()[19];
        }


        /**
         * Clears the value of the 'field_last_traded_time' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldLastTradedTime() {
            field_last_traded_time = null;
            fieldSetFlags()[19] = false;
            return this;
        }

        /**
         * Gets the value of the 'label' field.
         * @return The value.
         */
        public java.lang.CharSequence getLabel() {
            return label;
        }


        /**
         * Sets the value of the 'label' field.
         * @param value The value of 'label'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setLabel(java.lang.CharSequence value) {
            validate(fields()[20], value);
            this.label = value;
            fieldSetFlags()[20] = true;
            return this;
        }

        /**
         * Checks whether the 'label' field has been set.
         * @return True if the 'label' field has been set, false otherwise.
         */
        public boolean hasLabel() {
            return fieldSetFlags()[20];
        }


        /**
         * Clears the value of the 'label' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearLabel() {
            label = null;
            fieldSetFlags()[20] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_best_bid_price' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldBestBidPrice() {
            return field_best_bid_price;
        }


        /**
         * Sets the value of the 'field_best_bid_price' field.
         * @param value The value of 'field_best_bid_price'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldBestBidPrice(java.lang.CharSequence value) {
            validate(fields()[21], value);
            this.field_best_bid_price = value;
            fieldSetFlags()[21] = true;
            return this;
        }

        /**
         * Checks whether the 'field_best_bid_price' field has been set.
         * @return True if the 'field_best_bid_price' field has been set, false otherwise.
         */
        public boolean hasFieldBestBidPrice() {
            return fieldSetFlags()[21];
        }


        /**
         * Clears the value of the 'field_best_bid_price' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldBestBidPrice() {
            field_best_bid_price = null;
            fieldSetFlags()[21] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_dynamic_reference_price' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldDynamicReferencePrice() {
            return field_dynamic_reference_price;
        }


        /**
         * Sets the value of the 'field_dynamic_reference_price' field.
         * @param value The value of 'field_dynamic_reference_price'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldDynamicReferencePrice(java.lang.CharSequence value) {
            validate(fields()[22], value);
            this.field_dynamic_reference_price = value;
            fieldSetFlags()[22] = true;
            return this;
        }

        /**
         * Checks whether the 'field_dynamic_reference_price' field has been set.
         * @return True if the 'field_dynamic_reference_price' field has been set, false otherwise.
         */
        public boolean hasFieldDynamicReferencePrice() {
            return fieldSetFlags()[22];
        }


        /**
         * Clears the value of the 'field_dynamic_reference_price' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldDynamicReferencePrice() {
            field_dynamic_reference_price = null;
            fieldSetFlags()[22] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_static_reference_price' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldStaticReferencePrice() {
            return field_static_reference_price;
        }


        /**
         * Sets the value of the 'field_static_reference_price' field.
         * @param value The value of 'field_static_reference_price'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldStaticReferencePrice(java.lang.CharSequence value) {
            validate(fields()[23], value);
            this.field_static_reference_price = value;
            fieldSetFlags()[23] = true;
            return this;
        }

        /**
         * Checks whether the 'field_static_reference_price' field has been set.
         * @return True if the 'field_static_reference_price' field has been set, false otherwise.
         */
        public boolean hasFieldStaticReferencePrice() {
            return fieldSetFlags()[23];
        }


        /**
         * Clears the value of the 'field_static_reference_price' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldStaticReferencePrice() {
            field_static_reference_price = null;
            fieldSetFlags()[23] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_low_price' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldLowPrice() {
            return field_low_price;
        }


        /**
         * Sets the value of the 'field_low_price' field.
         * @param value The value of 'field_low_price'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldLowPrice(java.lang.CharSequence value) {
            validate(fields()[24], value);
            this.field_low_price = value;
            fieldSetFlags()[24] = true;
            return this;
        }

        /**
         * Checks whether the 'field_low_price' field has been set.
         * @return True if the 'field_low_price' field has been set, false otherwise.
         */
        public boolean hasFieldLowPrice() {
            return fieldSetFlags()[24];
        }


        /**
         * Clears the value of the 'field_low_price' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldLowPrice() {
            field_low_price = null;
            fieldSetFlags()[24] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_high_price' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldHighPrice() {
            return field_high_price;
        }


        /**
         * Sets the value of the 'field_high_price' field.
         * @param value The value of 'field_high_price'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldHighPrice(java.lang.CharSequence value) {
            validate(fields()[25], value);
            this.field_high_price = value;
            fieldSetFlags()[25] = true;
            return this;
        }

        /**
         * Checks whether the 'field_high_price' field has been set.
         * @return True if the 'field_high_price' field has been set, false otherwise.
         */
        public boolean hasFieldHighPrice() {
            return fieldSetFlags()[25];
        }


        /**
         * Clears the value of the 'field_high_price' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldHighPrice() {
            field_high_price = null;
            fieldSetFlags()[25] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_cumul_volume_echange' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldCumulVolumeEchange() {
            return field_cumul_volume_echange;
        }


        /**
         * Sets the value of the 'field_cumul_volume_echange' field.
         * @param value The value of 'field_cumul_volume_echange'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldCumulVolumeEchange(java.lang.CharSequence value) {
            validate(fields()[26], value);
            this.field_cumul_volume_echange = value;
            fieldSetFlags()[26] = true;
            return this;
        }

        /**
         * Checks whether the 'field_cumul_volume_echange' field has been set.
         * @return True if the 'field_cumul_volume_echange' field has been set, false otherwise.
         */
        public boolean hasFieldCumulVolumeEchange() {
            return fieldSetFlags()[26];
        }


        /**
         * Clears the value of the 'field_cumul_volume_echange' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldCumulVolumeEchange() {
            field_cumul_volume_echange = null;
            fieldSetFlags()[26] = false;
            return this;
        }

        /**
         * Gets the value of the 'field_last_traded_price' field.
         * @return The value.
         */
        public java.lang.CharSequence getFieldLastTradedPrice() {
            return field_last_traded_price;
        }


        /**
         * Sets the value of the 'field_last_traded_price' field.
         * @param value The value of 'field_last_traded_price'.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder setFieldLastTradedPrice(java.lang.CharSequence value) {
            validate(fields()[27], value);
            this.field_last_traded_price = value;
            fieldSetFlags()[27] = true;
            return this;
        }

        /**
         * Checks whether the 'field_last_traded_price' field has been set.
         * @return True if the 'field_last_traded_price' field has been set, false otherwise.
         */
        public boolean hasFieldLastTradedPrice() {
            return fieldSetFlags()[27];
        }


        /**
         * Clears the value of the 'field_last_traded_price' field.
         * @return This builder.
         */
        public com.popupd.util.BourseData.Builder clearFieldLastTradedPrice() {
            field_last_traded_price = null;
            fieldSetFlags()[27] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public BourseData build() {
            try {
                BourseData record = new BourseData();
                record.field_date_application = fieldSetFlags()[0] ? this.field_date_application : (java.lang.CharSequence) defaultValue(fields()[0]);
                record.field_closing_price = fieldSetFlags()[1] ? this.field_closing_price : (java.lang.CharSequence) defaultValue(fields()[1]);
                record.field_difference = fieldSetFlags()[2] ? this.field_difference : (java.lang.CharSequence) defaultValue(fields()[2]);
                record.field_var_veille = fieldSetFlags()[3] ? this.field_var_veille : (java.lang.CharSequence) defaultValue(fields()[3]);
                record.field_best_ask_size = fieldSetFlags()[4] ? this.field_best_ask_size : (java.lang.CharSequence) defaultValue(fields()[4]);
                record.field_transact_time = fieldSetFlags()[5] ? this.field_transact_time : (java.lang.CharSequence) defaultValue(fields()[5]);
                record.field_cours_cloture = fieldSetFlags()[6] ? this.field_cours_cloture : (java.lang.CharSequence) defaultValue(fields()[6]);
                record.field_cours_ajuste = fieldSetFlags()[7] ? this.field_cours_ajuste : (java.lang.CharSequence) defaultValue(fields()[7]);
                record.field_cumul_titres_echanges = fieldSetFlags()[8] ? this.field_cumul_titres_echanges : (java.lang.CharSequence) defaultValue(fields()[8]);
                record.field_best_bid_size = fieldSetFlags()[9] ? this.field_best_bid_size : (java.lang.CharSequence) defaultValue(fields()[9]);
                record.field_capitalisation = fieldSetFlags()[10] ? this.field_capitalisation : (java.lang.CharSequence) defaultValue(fields()[10]);
                record.field_opening_price = fieldSetFlags()[11] ? this.field_opening_price : (java.lang.CharSequence) defaultValue(fields()[11]);
                record.field_total_trades = fieldSetFlags()[12] ? this.field_total_trades : (java.lang.CharSequence) defaultValue(fields()[12]);
                record.field_cours_courant = fieldSetFlags()[13] ? this.field_cours_courant : (java.lang.CharSequence) defaultValue(fields()[13]);
                record.field_best_ask_price = fieldSetFlags()[14] ? this.field_best_ask_price : (java.lang.CharSequence) defaultValue(fields()[14]);
                record.sous_secteur = fieldSetFlags()[15] ? this.sous_secteur : (java.lang.CharSequence) defaultValue(fields()[15]);
                record.ticker = fieldSetFlags()[16] ? this.ticker : (java.lang.CharSequence) defaultValue(fields()[16]);
                record.field_instrument_var_year = fieldSetFlags()[17] ? this.field_instrument_var_year : (java.lang.CharSequence) defaultValue(fields()[17]);
                record.field_var_pto = fieldSetFlags()[18] ? this.field_var_pto : (java.lang.CharSequence) defaultValue(fields()[18]);
                record.field_last_traded_time = fieldSetFlags()[19] ? this.field_last_traded_time : (java.lang.CharSequence) defaultValue(fields()[19]);
                record.label = fieldSetFlags()[20] ? this.label : (java.lang.CharSequence) defaultValue(fields()[20]);
                record.field_best_bid_price = fieldSetFlags()[21] ? this.field_best_bid_price : (java.lang.CharSequence) defaultValue(fields()[21]);
                record.field_dynamic_reference_price = fieldSetFlags()[22] ? this.field_dynamic_reference_price : (java.lang.CharSequence) defaultValue(fields()[22]);
                record.field_static_reference_price = fieldSetFlags()[23] ? this.field_static_reference_price : (java.lang.CharSequence) defaultValue(fields()[23]);
                record.field_low_price = fieldSetFlags()[24] ? this.field_low_price : (java.lang.CharSequence) defaultValue(fields()[24]);
                record.field_high_price = fieldSetFlags()[25] ? this.field_high_price : (java.lang.CharSequence) defaultValue(fields()[25]);
                record.field_cumul_volume_echange = fieldSetFlags()[26] ? this.field_cumul_volume_echange : (java.lang.CharSequence) defaultValue(fields()[26]);
                record.field_last_traded_price = fieldSetFlags()[27] ? this.field_last_traded_price : (java.lang.CharSequence) defaultValue(fields()[27]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<BourseData>
            WRITER$ = (org.apache.avro.io.DatumWriter<BourseData>)MODEL$.createDatumWriter(SCHEMA$);

    @Override public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<BourseData>
            READER$ = (org.apache.avro.io.DatumReader<BourseData>)MODEL$.createDatumReader(SCHEMA$);

    @Override public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override protected boolean hasCustomCoders() { return true; }

    @Override public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException
    {
        out.writeString(this.field_date_application);

        out.writeString(this.field_closing_price);

        out.writeString(this.field_difference);

        out.writeString(this.field_var_veille);

        out.writeString(this.field_best_ask_size);

        out.writeString(this.field_transact_time);

        out.writeString(this.field_cours_cloture);

        out.writeString(this.field_cours_ajuste);

        out.writeString(this.field_cumul_titres_echanges);

        out.writeString(this.field_best_bid_size);

        out.writeString(this.field_capitalisation);

        out.writeString(this.field_opening_price);

        out.writeString(this.field_total_trades);

        out.writeString(this.field_cours_courant);

        out.writeString(this.field_best_ask_price);

        out.writeString(this.sous_secteur);

        out.writeString(this.ticker);

        out.writeString(this.field_instrument_var_year);

        out.writeString(this.field_var_pto);

        out.writeString(this.field_last_traded_time);

        out.writeString(this.label);

        out.writeString(this.field_best_bid_price);

        out.writeString(this.field_dynamic_reference_price);

        out.writeString(this.field_static_reference_price);

        out.writeString(this.field_low_price);

        out.writeString(this.field_high_price);

        out.writeString(this.field_cumul_volume_echange);

        out.writeString(this.field_last_traded_price);

    }

    @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException
    {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.field_date_application = in.readString(this.field_date_application instanceof Utf8 ? (Utf8)this.field_date_application : null);

            this.field_closing_price = in.readString(this.field_closing_price instanceof Utf8 ? (Utf8)this.field_closing_price : null);

            this.field_difference = in.readString(this.field_difference instanceof Utf8 ? (Utf8)this.field_difference : null);

            this.field_var_veille = in.readString(this.field_var_veille instanceof Utf8 ? (Utf8)this.field_var_veille : null);

            this.field_best_ask_size = in.readString(this.field_best_ask_size instanceof Utf8 ? (Utf8)this.field_best_ask_size : null);

            this.field_transact_time = in.readString(this.field_transact_time instanceof Utf8 ? (Utf8)this.field_transact_time : null);

            this.field_cours_cloture = in.readString(this.field_cours_cloture instanceof Utf8 ? (Utf8)this.field_cours_cloture : null);

            this.field_cours_ajuste = in.readString(this.field_cours_ajuste instanceof Utf8 ? (Utf8)this.field_cours_ajuste : null);

            this.field_cumul_titres_echanges = in.readString(this.field_cumul_titres_echanges instanceof Utf8 ? (Utf8)this.field_cumul_titres_echanges : null);

            this.field_best_bid_size = in.readString(this.field_best_bid_size instanceof Utf8 ? (Utf8)this.field_best_bid_size : null);

            this.field_capitalisation = in.readString(this.field_capitalisation instanceof Utf8 ? (Utf8)this.field_capitalisation : null);

            this.field_opening_price = in.readString(this.field_opening_price instanceof Utf8 ? (Utf8)this.field_opening_price : null);

            this.field_total_trades = in.readString(this.field_total_trades instanceof Utf8 ? (Utf8)this.field_total_trades : null);

            this.field_cours_courant = in.readString(this.field_cours_courant instanceof Utf8 ? (Utf8)this.field_cours_courant : null);

            this.field_best_ask_price = in.readString(this.field_best_ask_price instanceof Utf8 ? (Utf8)this.field_best_ask_price : null);

            this.sous_secteur = in.readString(this.sous_secteur instanceof Utf8 ? (Utf8)this.sous_secteur : null);

            this.ticker = in.readString(this.ticker instanceof Utf8 ? (Utf8)this.ticker : null);

            this.field_instrument_var_year = in.readString(this.field_instrument_var_year instanceof Utf8 ? (Utf8)this.field_instrument_var_year : null);

            this.field_var_pto = in.readString(this.field_var_pto instanceof Utf8 ? (Utf8)this.field_var_pto : null);

            this.field_last_traded_time = in.readString(this.field_last_traded_time instanceof Utf8 ? (Utf8)this.field_last_traded_time : null);

            this.label = in.readString(this.label instanceof Utf8 ? (Utf8)this.label : null);

            this.field_best_bid_price = in.readString(this.field_best_bid_price instanceof Utf8 ? (Utf8)this.field_best_bid_price : null);

            this.field_dynamic_reference_price = in.readString(this.field_dynamic_reference_price instanceof Utf8 ? (Utf8)this.field_dynamic_reference_price : null);

            this.field_static_reference_price = in.readString(this.field_static_reference_price instanceof Utf8 ? (Utf8)this.field_static_reference_price : null);

            this.field_low_price = in.readString(this.field_low_price instanceof Utf8 ? (Utf8)this.field_low_price : null);

            this.field_high_price = in.readString(this.field_high_price instanceof Utf8 ? (Utf8)this.field_high_price : null);

            this.field_cumul_volume_echange = in.readString(this.field_cumul_volume_echange instanceof Utf8 ? (Utf8)this.field_cumul_volume_echange : null);

            this.field_last_traded_price = in.readString(this.field_last_traded_price instanceof Utf8 ? (Utf8)this.field_last_traded_price : null);

        } else {
            for (int i = 0; i < 28; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.field_date_application = in.readString(this.field_date_application instanceof Utf8 ? (Utf8)this.field_date_application : null);
                        break;

                    case 1:
                        this.field_closing_price = in.readString(this.field_closing_price instanceof Utf8 ? (Utf8)this.field_closing_price : null);
                        break;

                    case 2:
                        this.field_difference = in.readString(this.field_difference instanceof Utf8 ? (Utf8)this.field_difference : null);
                        break;

                    case 3:
                        this.field_var_veille = in.readString(this.field_var_veille instanceof Utf8 ? (Utf8)this.field_var_veille : null);
                        break;

                    case 4:
                        this.field_best_ask_size = in.readString(this.field_best_ask_size instanceof Utf8 ? (Utf8)this.field_best_ask_size : null);
                        break;

                    case 5:
                        this.field_transact_time = in.readString(this.field_transact_time instanceof Utf8 ? (Utf8)this.field_transact_time : null);
                        break;

                    case 6:
                        this.field_cours_cloture = in.readString(this.field_cours_cloture instanceof Utf8 ? (Utf8)this.field_cours_cloture : null);
                        break;

                    case 7:
                        this.field_cours_ajuste = in.readString(this.field_cours_ajuste instanceof Utf8 ? (Utf8)this.field_cours_ajuste : null);
                        break;

                    case 8:
                        this.field_cumul_titres_echanges = in.readString(this.field_cumul_titres_echanges instanceof Utf8 ? (Utf8)this.field_cumul_titres_echanges : null);
                        break;

                    case 9:
                        this.field_best_bid_size = in.readString(this.field_best_bid_size instanceof Utf8 ? (Utf8)this.field_best_bid_size : null);
                        break;

                    case 10:
                        this.field_capitalisation = in.readString(this.field_capitalisation instanceof Utf8 ? (Utf8)this.field_capitalisation : null);
                        break;

                    case 11:
                        this.field_opening_price = in.readString(this.field_opening_price instanceof Utf8 ? (Utf8)this.field_opening_price : null);
                        break;

                    case 12:
                        this.field_total_trades = in.readString(this.field_total_trades instanceof Utf8 ? (Utf8)this.field_total_trades : null);
                        break;

                    case 13:
                        this.field_cours_courant = in.readString(this.field_cours_courant instanceof Utf8 ? (Utf8)this.field_cours_courant : null);
                        break;

                    case 14:
                        this.field_best_ask_price = in.readString(this.field_best_ask_price instanceof Utf8 ? (Utf8)this.field_best_ask_price : null);
                        break;

                    case 15:
                        this.sous_secteur = in.readString(this.sous_secteur instanceof Utf8 ? (Utf8)this.sous_secteur : null);
                        break;

                    case 16:
                        this.ticker = in.readString(this.ticker instanceof Utf8 ? (Utf8)this.ticker : null);
                        break;

                    case 17:
                        this.field_instrument_var_year = in.readString(this.field_instrument_var_year instanceof Utf8 ? (Utf8)this.field_instrument_var_year : null);
                        break;

                    case 18:
                        this.field_var_pto = in.readString(this.field_var_pto instanceof Utf8 ? (Utf8)this.field_var_pto : null);
                        break;

                    case 19:
                        this.field_last_traded_time = in.readString(this.field_last_traded_time instanceof Utf8 ? (Utf8)this.field_last_traded_time : null);
                        break;

                    case 20:
                        this.label = in.readString(this.label instanceof Utf8 ? (Utf8)this.label : null);
                        break;

                    case 21:
                        this.field_best_bid_price = in.readString(this.field_best_bid_price instanceof Utf8 ? (Utf8)this.field_best_bid_price : null);
                        break;

                    case 22:
                        this.field_dynamic_reference_price = in.readString(this.field_dynamic_reference_price instanceof Utf8 ? (Utf8)this.field_dynamic_reference_price : null);
                        break;

                    case 23:
                        this.field_static_reference_price = in.readString(this.field_static_reference_price instanceof Utf8 ? (Utf8)this.field_static_reference_price : null);
                        break;

                    case 24:
                        this.field_low_price = in.readString(this.field_low_price instanceof Utf8 ? (Utf8)this.field_low_price : null);
                        break;

                    case 25:
                        this.field_high_price = in.readString(this.field_high_price instanceof Utf8 ? (Utf8)this.field_high_price : null);
                        break;

                    case 26:
                        this.field_cumul_volume_echange = in.readString(this.field_cumul_volume_echange instanceof Utf8 ? (Utf8)this.field_cumul_volume_echange : null);
                        break;

                    case 27:
                        this.field_last_traded_price = in.readString(this.field_last_traded_price instanceof Utf8 ? (Utf8)this.field_last_traded_price : null);
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}









